name: Publishing Docker images
on:
  push:
    branches:
      - '**'

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

  create-docker-image:
    runs-on: ubuntu-latest
    needs: create-image
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."